# Generated by Django 2.1.9 on 2019-06-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='age',
        ),
        migrations.RemoveField(
            model_name='item',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
